import "bootstrap/dist/css/bootstrap.css"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from "./Components/Navbar/Navbar"
import Script from "next/script"
import Image from "next/image"
import test from "../public/next.svg"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hobbies',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossOrigin="anonymous"
      />
        </body>

        
    </html>
  )
}
